eclipse-tractusx/traceability-foss

.github/workflows/e2e-tests-xray_frontend.yml, .github/workflows/publish-documentation.yaml, .github/workflows/veracode_backend.yml, .github/workflows/veracode_frontend.yml, CHANGELOG.md, README.md, docs/.markdownlint.yaml, docs/src/diagram-replacer/extract.js, docs/src/diagram-replacer/replace.js, docs/src/docs/arc42/quality/quality-tree.adoc, docs/src/post-processing/fix_headers.js, docs/src/post-processing/fix_https_links.js, docs/src/post-processing/fix_no_emphasis.js, docs/src/post-processing/fix_relative_links.js, frontend/INSTALL.md
- Updated Publish documentation workflow to convert and deploy documentation as markdown (.md)
- Bumped cypress-io/github-action from 5.6.1 to 5.6.2
- Bumped veracode/veracode-uploadandscan-action@0.2.5 to 0.2.6
- Updated catena links from readme to reflext tractusx links
=> Updated documentation links and markdown documentation workflow

.github/workflows/xray-cucumber.yaml, CHANGELOG.md, tx-cucumber-tests/src/test/java/org/eclipse/tractusx/traceability/test/TraceabilityTestStepDefinition.java, tx-cucumber-tests/src/test/resources/features/1_TRACEFOSS-1125.feature, tx-cucumber-tests/src/test/resources/features/2_TRACEFOSS-608.feature
---
name: Modify cucumber. test execution
about: 'template for PRs that ensures basic information is provided'
title: 'feat: TRACEFOSS-1220 fix duplication of test execution when new features are introduced to jira'
---
- added another test based on existing logic in cucumber test engine
- fixed situation when targetDate is not provided in investigation test execution
- adjusted pipeline to remove repository feature files before extracting jira downloaded ones to avoid execution duplication
=> Adjusted cucumber test action not to duplicate execution of repository and jira downloaded feature files

CHANGELOG.md, DEPENDENCIES_BACKEND, README.md, dev/README.md, tx-backend/openapi/traceability-foss-backend.json, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/infrastructure/base/irs/model/response/JobDetailResponse.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/infrastructure/base/irs/model/response/Submodel.java, tx-backend/src/main/resources/application.yml, tx-backend/testdata/CX_Testdata_MessagingTest_v0.0.7.json
This pr updates the test data and the corresponding configuration for the unused registry client library. 
- Configuration for left and right policies to use registry client library
- Update asBuild test data to 1.5.3 and asPlanned to 1.5.1
=> feature: TRACEFOSS-2235 update test data to asBuilt 1.5.3 and asPlanned 1.5.1

.github/workflows/e2e-tests-xray_frontend.yml, CHANGELOG.md, docs/src/uml-diagrams/concept/TRACEFOSS-1423/domain-model.puml, pom.xml, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/infrastructure/base/irs/model/response/JobDetailResponse.java, tx-backend/src/main/resources/data/irs_job_response_with_null_manufacturer_names.json, tx-backend/src/test/java/org/eclipse/tractusx/traceability/assets/infrastructure/repository/rest/irs/model/JobDetailResponseTest.java
- added handling for null manufacturerName in IrsJobResponse, if null is passed it is replaced with "UNKNOWN_MANUFACTURER"
=> fix: TRACEFOSS-XXX handling manufacturerName null situation from IrsJobResponse

CHANGELOG.md, frontend/src/app/modules/shared/components/multi-select-autocomplete/multi-select-autocomplete.component.html, frontend/src/app/modules/shared/components/multi-select-autocomplete/multi-select-autocomplete.component.spec.ts, frontend/src/app/modules/shared/components/multi-select-autocomplete/multi-select-autocomplete.component.ts
Fixed  bugs in local filtering of parts table, results in:
- Click on X will clear the input field and the distinct values list 
- Empty input field will clear the distinct values list 
- Remove of characters will trigger new search 
- Press enter on empty input field will not trigger search 
- Select all checkbox should select all values in disctinct values list. 
=> fixed several bugs in frontend filtering in parts table

CHANGELOG.md, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/application/asbuilt/rest/AssetAsBuiltController.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/application/asplanned/rest/AssetAsPlannedController.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/application/base/service/AssetBaseService.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/domain/base/AssetRepository.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/domain/base/service/AbstractAssetBaseService.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/infrastructure/asbuilt/repository/AssetAsBuiltRepositoryImpl.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/infrastructure/asplanned/repository/AssetAsPlannedRepositoryImpl.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/common/config/ErrorHandlingConfig.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/common/repository/SqlUtil.java, tx-backend/src/test/java/org/eclipse/tractusx/traceability/integration/assets/AssetAsBuiltControllerFilterValuesIT.java, tx-backend/src/test/java/org/eclipse/tractusx/traceability/integration/assets/AssetAsPlannedControllerFilterValuesIT.java
Changed:
- Param for owner in autocomplete api changed to ENUM type to avoid SQL injections
=> chore: TRACEFOSS-2882 SQL injection issue

.github/workflows/argo.yml, CHANGELOG.md, frontend/cypress/integration/pages/QualityInvestigationsPage.ts, frontend/cypress/support/step_definitions/dashboard.ts, frontend/cypress/support/step_definitions/login.ts, frontend/cypress/support/step_definitions/menu.ts, frontend/cypress/support/step_definitions/quality-investigations.ts, frontend/src/app/mocks/services/dashboard-mock/dashboard.model.ts, frontend/src/app/modules/page/dashboard/core/dashboard.assembler.spec.ts, frontend/src/app/modules/page/dashboard/core/dashboard.assembler.ts, frontend/src/app/modules/page/dashboard/model/dashboard.model.ts, frontend/src/app/modules/page/dashboard/presentation/dashboard.component.ts, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/application/dashboard/mapper/DashboardResponseMapper.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/domain/dashboard/model/Dashboard.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/domain/dashboard/service/DashboardServiceImpl.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/qualitynotification/domain/repository/QualityNotificationRepository.java, tx-backend/src/test/java/org/eclipse/tractusx/traceability/assets/application/rest/DashboardControllerTest.java, tx-backend/src/test/java/org/eclipse/tractusx/traceability/integration/assets/DashboardControllerIT.java, tx-models/src/main/java/assets/response/DashboardResponse.java
- Added implementation for cucumber tests for quality investigations
- Added new fields to dashboard response
=> Added cucumber tests for quality investigations

.github/workflows/argo.yml, CHANGELOG.md, DEPENDENCIES_BACKEND, DEPENDENCIES_FRONTEND, frontend/src/app/modules/shared/components/multi-select-autocomplete/multi-select-autocomplete.component.html, frontend/src/app/modules/shared/components/multi-select-autocomplete/multi-select-autocomplete.component.spec.ts, frontend/src/app/modules/shared/components/multi-select-autocomplete/multi-select-autocomplete.component.ts, pom.xml, tx-backend/src/main/java/org/eclipse/tractusx/traceability/qualitynotification/domain/base/exception/SendNotificationException.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/qualitynotification/domain/base/service/AbstractQualityNotificationService.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/qualitynotification/domain/base/service/EdcNotificationServiceImpl.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/qualitynotification/domain/base/service/NotificationPublisherService.java, tx-backend/src/test/java/org/eclipse/tractusx/traceability/qualitynotification/domain/service/EdcNotificationServiceImplTest.java, tx-backend/src/test/java/org/eclipse/tractusx/traceability/qualitynotification/domain/service/NotificationPublisherServiceTest.java, tx-cucumber-tests/pom.xml, tx-cucumber-tests/src/test/java/org/eclipse/tractusx/traceability/test/TraceabilityTestStepDefinition.java, tx-cucumber-tests/src/test/java/org/eclipse/tractusx/traceability/test/exteption/MissingStepDefinitionException.java, tx-cucumber-tests/src/test/resources/features/10_TRACEFOSS-1125.feature, tx-cucumber-tests/src/test/resources/features/1_TRACEFOSS-1393.feature, tx-cucumber-tests/src/test/resources/features/2_TRACEFOSS-600.feature, tx-cucumber-tests/src/test/resources/features/3_TRACEFOSS-936.feature, tx-cucumber-tests/src/test/resources/features/4_TRACEFOSS-938.feature, tx-cucumber-tests/src/test/resources/features/5_TRACEFOSS-1625.feature, tx-cucumber-tests/src/test/resources/features/6_TRACEFOSS-382.feature, tx-cucumber-tests/src/test/resources/features/7_TRACEFOSS-1090.feature, tx-cucumber-tests/src/test/resources/features/8_TRACEFOSS-608.feature
- Separation of auto complete mechanism (selected / searched elements)
- Added new step definition for cucumber tests "I use assets with ids {string}" allowing to specify assets used for notification creation
- Cucumber test steps for creating notifications no longer support default assetId when no asset is provided with previous step
- Upgraded the Upload_Testdata job in Argo Workflow to fix bugs
- Removed Cucumber tests steps for creating alerts with two parts as new step definition is enough for the same feature
=> Added separation of autocomplete mechanism selected/searched elements

.github/workflows/argo.yml, .github/workflows/codeql.yml, .github/workflows/dependencies.yaml, .github/workflows/dependency-check.yml, .github/workflows/docker-image-main_backend.yml, .github/workflows/docker-image-tag-release.yaml, .github/workflows/eclipse-dash.yml, .github/workflows/publish-documentation.yaml, .github/workflows/pull-request_backend.yml, .github/workflows/release.yaml, .github/workflows/sonar-scan-backend.yml, .github/workflows/spotbugs.yml, .github/workflows/trivy.yml, .github/workflows/veracode_backend.yml, .github/workflows/xray-cucumber.yaml, CHANGELOG.md, frontend/src/app/modules/shared/components/dateTime/dateTime.component.html, frontend/src/app/modules/shared/components/dateTime/dateTime.component.ts, pom.xml, tx-backend/pom.xml
- Restricted datefield on investigation creation to be only clickable and not editable
- bump aquasecurity/trivy-action from 0.14.0 to 0.16.0
- bump actions/setup-python from 4 to 5
- bump mikefarah/yq from 4.40.2 to 4.40.5
- bump actions/setup-java from 3 to 4
- bump org.apache.maven.plugins:maven-jxr-plugin from 3.3.0 to 3.3.1
- bump org.apache.maven.plugins:maven-checkstyle-plugin from 3.3.0 to 3.3.1
- bump schedlock.version from 5.9.1 to 5.10.0
=> Version bumps 

.github/workflows/e2e-tests-xray_frontend.yml, .github/workflows/eclipse-dash.yml, .github/workflows/pull-request_backend.yml, .github/workflows/trivy.yml, CHANGELOG.md, pom.xml, tx-backend/openapi/traceability-foss-backend.json, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/application/importpoc/rest/PolicyController.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/infrastructure/base/irs/IrsCallbackController.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/submodel/application/rest/SubmodelController.java
- Bumped jacoco-maven-plugin from 0.8.8 to 0.8.11
- Bumped cypress-io/github-action from 6.6.0 to 6.6.1
- Bumped tj-actions/changed-files from v41 to v42
- Fixed some response type descriptions within swagger documentation
=> chore: bump versions of dependencies and fix response descriptions

CHANGELOG.md, DEPENDENCIES_FRONTEND, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/application/importpoc/rest/ImportController.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/domain/base/AssetRepository.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/domain/importpoc/exception/PublishAssetException.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/domain/importpoc/service/PublishServiceImpl.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/infrastructure/asbuilt/repository/AssetAsBuiltRepositoryImpl.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/infrastructure/asplanned/repository/AssetAsPlannedRepositoryImpl.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/common/config/ErrorHandlingConfig.java, tx-backend/src/test/java/org/eclipse/tractusx/traceability/integration/importdata/ImportControllerIT.java, tx-models/src/main/java/assets/importpoc/ValidationResponse.java
- Error handling when publishing assets
=> chore: update error handling when publishing assets

tx-cucumber-tests/src/test/java/org/eclipse/tractusx/traceability/test/TraceabilityTestStepDefinition.java, tx-cucumber-tests/src/test/java/org/eclipse/tractusx/traceability/test/tooling/NotificationTypeEnum.java, tx-cucumber-tests/src/test/java/org/eclipse/tractusx/traceability/test/tooling/rest/RestProvider.java
=> chore: adjust cucumber tests

docs/src/uml-diagrams/arc42/cross-cutting/erm-trace-x.puml, tx-backend/src/main/resources/db/migration/V21__remove_notification_connection_from_as_planned.sql, tx-backend/src/test/java/org/eclipse/tractusx/traceability/integration/common/support/DatabaseSupport.java
=> chore: #706 update documentation

CHANGELOG.md, COMPATIBILITY_MATRIX.md, charts/traceability-foss/CHANGELOG.md, charts/traceability-foss/Chart.yaml, charts/traceability-foss/charts/backend/Chart.yaml, charts/traceability-foss/charts/frontend/Chart.yaml, frontend/package.json, pom.xml, tx-backend/src/main/java/org/eclipse/tractusx/traceability/common/model/SecurityUtils.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/notification/infrastructure/edc/model/EDCNotification.java
- #616 Allow edc notification update with empty asset list
=> feature: 616 Allow edc notification update with empty asset list, release 10.8.0

CHANGELOG.md, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/application/asbuilt/rest/AssetAsBuiltController.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/application/asplanned/rest/AssetAsPlannedController.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/application/base/service/AssetBaseService.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/domain/base/AssetRepository.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/domain/base/service/AbstractAssetBaseService.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/infrastructure/asbuilt/repository/AssetAsBuiltRepositoryImpl.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/infrastructure/asplanned/repository/AssetAsPlannedRepositoryImpl.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/common/repository/CriteriaUtility.java, tx-backend/src/test/java/org/eclipse/tractusx/traceability/assets/domain/base/service/AbstractAssetBaseServiceTest.java, tx-backend/src/test/java/org/eclipse/tractusx/traceability/integration/assets/AssetAsBuiltControllerFilterValuesIT.java, tx-backend/src/test/java/org/eclipse/tractusx/traceability/integration/assets/AssetAsPlannedControllerFilterValuesIT.java, tx-backend/src/test/java/org/eclipse/tractusx/traceability/integration/assets/asbuilt/infrastructure/repository/AssetAsBuiltRepositoryIT.java, tx-backend/src/test/java/org/eclipse/tractusx/traceability/integration/assets/asplanned/infrastructure/repository/AssetAsPlannedRepositoryIT.java
resolves #859 
This PR introduces functionality to the autocomplete API to handle a given list of assets. With this, the API only searches in a given set of assets in the database to minimize workload. 
The new query parameter `inAssetIds` accepts multiple asset IDs with comma separation. For e.g. :
`/api/assets/as-planned/distinctFilterValues?fieldName=nameAtManufacturer&size=100&inAssetIds=urn%3Auuid%3A0733946c-59c6-41ae-9570-cb43a6e4da01%2Curn%3Auuid%3A0733946c-59c6-41ae-9570-cb43a6e4eb01`
returns only two distinct autocomplete values for the given asset IDs 
- urn:uuid:0733946c-59c6-41ae-9570-cb43a6e4da01
- urn:uuid:0733946c-59c6-41ae-9570-cb43a6e4eb01
- #859 Enable autocomplete API to filter for given assets
Please ensure to do as many of the following checks as possible, before …
=> feature: #859 enable autocomplete API to filter for given assets

CHANGELOG.md, tx-backend/src/main/java/org/eclipse/tractusx/traceability/contracts/infrastructure/repository/ContractRepositoryImpl.java, tx-backend/src/test/java/org/eclipse/tractusx/traceability/integration/contracts/ContractControllerIT.java
This PR fixes a bug in the /contracts API where an HTTP404 is returned in case of no present contract agreement IDs. Since this API returns a PageResult, the response should be HTTP 200 with an empty PageResult. This bug was discovered with the migration to EDC 0.7.0 (#778)
Warning logs are also added with this PR.
=> bug: #778 return empty page result insteadof http 404

CHANGELOG.md, CONTRIBUTING.md, LICENSE_non-code, NOTICE.md, README.md
This PR addresses issue #1017.
The following was performed to achieve compliance with TRG 7:
- added the new `LICENSE_non-code` file containing the CC-BY-4.0 license in the repository root
- added the "Project Licenses" & "Terms of Use" sections in `CONTRIBUTING.md`
- adapted the "Declared Project License" section in `NOTICE.md`
Additionally, the `README` was adapted since it also contains licensing information.
=> chore: Update licensing and legal docs for TRG 7

COMPATIBILITY_MATRIX.md
=> fix link COMPATIBILITY_MATRIX.md

tx-cucumber-tests/src/test/java/org/eclipse/tractusx/traceability/test/validator/NotificationValidator.java, tx-models/src/main/java/notification/response/NotificationResponse.java
=> feature(refactoring):962 refactored e2e-test.

frontend/src/app/modules/shared/components/notification-reason/notification-reason.component.html, frontend/src/app/modules/shared/components/notification-reason/notification-reason.component.scss
resolves eclipse-tractusx/traceability-foss#753
=> feature(notification): #753 align layout

frontend/src/app/modules/shared/components/notification-reason/notification-reason.component.ts
=> chore(notification): 962 fix message direction

tx-backend/src/main/java/org/eclipse/tractusx/traceability/common/config/ErrorHandlingConfig.java, tx-backend/src/test/java/org/eclipse/tractusx/traceability/integration/common/support/IrsApiSupport.java, tx-backend/src/test/java/org/eclipse/tractusx/traceability/integration/policy/PolicyControllerIT.java, tx-backend/src/test/resources/stubs/irs/policies/response_400_createPolicy.json, tx-backend/src/test/resources/stubs/irs/policies/response_400_get_policyById.json, tx-backend/src/test/resources/stubs/irs/policies/response_404_get_policyById.json, tx-models/src/main/java/assets/importpoc/IRSErrorResponse.java
resolves eclipse-tractusx/traceability-foss#965
=> feature(chore):965 added error handling for irs response

frontend/src/app/modules/page/admin/presentation/policy-management/policy-editor/policy-editor.component.html, frontend/src/app/modules/page/admin/presentation/policy-management/policy-editor/policy-editor.component.spec.ts, frontend/src/app/modules/page/admin/presentation/policy-management/policy-editor/policy-editor.component.ts, frontend/src/assets/locales/de/common.json, frontend/src/assets/locales/en/common.json
#832 implemented policy management in frontend (feedback)
resolves eclipse-tractusx/traceability-foss#832
=> chore(policies): 832 implemented feedback

frontend/src/app/modules/shared/components/notification-reason/notification-reason.component.ts
- #753 correctly display text messages
resolves eclipse-tractusx/traceability-foss#753
=> chore(messages): 753 correctly display messages

tx-backend/src/main/java/org/eclipse/tractusx/traceability/common/mapper/NotificationMapper.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/notification/application/notification/mapper/NotificationResponseMapper.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/notification/domain/base/model/Notification.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/notification/domain/base/service/AbstractNotificationService.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/notification/infrastructure/notification/model/NotificationEntity.java, tx-backend/src/test/java/org/eclipse/tractusx/traceability/integration/bpn/mapping/BpnMappingControllerIT.java
- #962 Removed initial notification message for notification flow
=> feature(chore):962 fixed sentToBpn.

tx-backend/src/main/resources/db/migration/R__create_contract_agreement_view.sql
=> feature(chore):985 Added notification contracts.

tx-backend/src/main/java/org/eclipse/tractusx/traceability/bpn/infrastructure/client/BpdmClient.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/common/config/ApplicationStartupConfig.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/contracts/domain/model/Contract.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/contracts/domain/model/ContractAgreement.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/contracts/domain/repository/ContractRepository.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/contracts/domain/service/ContractServiceImpl.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/contracts/infrastructure/model/ContractAgreementEntity.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/contracts/infrastructure/repository/ContractRepositoryImpl.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/contracts/infrastructure/repository/ContractSpecification.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/contracts/infrastructure/repository/JpaContractAgreementRepository.java, tx-backend/src/main/resources/db/migration/R__create_contract_agreement_view.sql, tx-backend/src/main/resources/db/migration/V25__create_contract_agreements.sql, tx-backend/src/test/java/org/eclipse/tractusx/traceability/integration/common/support/AssetsSupport.java, tx-backend/src/test/java/org/eclipse/tractusx/traceability/integration/contracts/ContractControllerIT.java
=> feature(chore):985 removed logging message.

tx-backend/src/main/java/org/eclipse/tractusx/traceability/contracts/infrastructure/repository/ContractRepositoryImpl.java
Fixed nullpointer within contractAgreementId list database query.
=> feature(chore):985 fixed nullpointer

frontend/src/app/modules/page/notifications/detail/edit/notification-edit.component.html, frontend/src/app/modules/page/notifications/detail/edit/notification-edit.component.ts, frontend/src/app/modules/shared/components/request-notification-new/notification-new-request.component.ts, frontend/src/assets/locales/de/common.json, frontend/src/assets/locales/en/common.json
#984 
resolves eclipse-tractusx/traceability-foss#984
=> chore(uux): 984 validation on notification save hover

CHANGELOG.md, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/infrastructure/asbuilt/repository/AssetAsBuiltRepositoryImpl.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/infrastructure/asplanned/repository/AssetAsPlannedRepositoryImpl.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/infrastructure/base/irs/JobRepositoryImpl.java, tx-backend/src/test/java/org/eclipse/tractusx/traceability/integration/assets/infrastructure/base/IrsCallbackControllerIT.java, tx-backend/src/test/resources/stubs/irs/get/jobs/id/response_200.json
This PR introduces a fix for #1082. For this, the transaction handling was adapted to no longer try to insert existing primary keys and also update the asset as a whole
=> bug: #1082 fix parts synchronization

.github/workflows/argo.yml, CHANGELOG.md, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/domain/base/model/AssetBase.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/domain/importpoc/service/AsyncPublishService.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/domain/importpoc/service/DtrService.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/infrastructure/base/irs/model/response/mapping/submodel/MapperHelper.java, tx-backend/src/test/java/org/eclipse/tractusx/traceability/integration/notification/investigation/InvestigationPolicyNotSupportedIT.java, tx-backend/testdata/import-test-data-CML1_v0.0.14.json, tx-backend/testdata/import-test-data-CNKC_v0.0.14.json
resolves eclipse-tractusx/traceability-foss#884
=> feature(chore):884 - fixxed mapper

AUTHORS.md, frontend/src/app/mocks/services/parts-mock/partsAsBuilt/partsAsBuilt.handler.ts
=> chore(docs): xxx added authors and todo technical debt

frontend/src/app/modules/shared/components/table/table.component.html, frontend/src/app/modules/shared/service/notification.service.ts, frontend/src/assets/locales/de/common.json, frontend/src/assets/locales/en/common.json
…g in notification creation/edit
#984 
=> chore(contracts): deactivated notification multi actions and fixed bug in notification creation

tx-backend/src/main/java/org/eclipse/tractusx/traceability/policies/infrastructure/PolicyRepositoryImpl.java, tx-backend/src/test/java/org/eclipse/tractusx/traceability/assets/infrastructure/base/irs/PolicyRepositoryImplTest.java, tx-backend/src/test/java/org/eclipse/tractusx/traceability/integration/common/support/IrsApiSupport.java, tx-backend/src/test/java/org/eclipse/tractusx/traceability/integration/notification/investigation/InvestigationPolicyExpirationIT.java, tx-backend/src/test/java/org/eclipse/tractusx/traceability/integration/notification/investigation/InvestigationPolicyNotSupportedIT.java, tx-backend/src/test/java/org/eclipse/tractusx/traceability/integration/policy/PolicyControllerIT.java, tx-backend/src/test/resources/stubs/irs/policies/request_create_policy.json, tx-backend/src/test/resources/stubs/irs/policies/response_200_get_policies_CONSTRAINTS_MISMATCHING.json, tx-backend/src/test/resources/stubs/irs/policies/response_200_get_policies_EXPIRED.json
=> bug: #639 update policies provider after crud operations on policies

.github/workflows/dependency-check.yml, CHANGELOG.md, pom.xml
This PR addresses #875.
- Removed maven profile "dependency-check" and dependency-check plugin definitions from root POM
- Changed workflow `dependency-check.yml` to use the dependency-check action, as mentioned in #875. This dramatically cuts down on workflow execution time. Additionally, the action allows for the same scanning configuration as the removed Maven profile.
=> fix: make dependency check action work (efficiently)

CHANGELOG.md, COMPATIBILITY_MATRIX.md
resolves eclipse-tractusx/traceability-foss#1173
=> chore(irs):1173 updated compatiblity matrix.

pom.xml, tx-backend/src/test/java/org/eclipse/tractusx/traceability/integration/notification/investigation/InvestigationPolicyExpirationIT.java
resolves eclipse-tractusx/traceability-foss#639
=> bug: #639 fix policy expired message

COMPATIBILITY_MATRIX.md, charts/traceability-foss/CHANGELOG.md, charts/traceability-foss/Chart.yaml, charts/traceability-foss/charts/backend/Chart.yaml, charts/traceability-foss/charts/frontend/Chart.yaml
- new helm chart version 1.3.41
- bump IRS helm dependency to 7.2.1
=> chore(charts): bump irs dependency to 7.2.1

frontend/src/app/modules/page/notifications/detail/notification-detail.component.ts, frontend/src/app/modules/page/notifications/presentation/notifications.component.ts, frontend/src/app/modules/shared/components/toasts/toast.service.ts, frontend/src/app/modules/shared/modules/notification/modal/actions/notification-action-modal.component.ts, frontend/src/app/modules/shared/service/notification-processing.service.spec.ts, frontend/src/app/modules/shared/service/notification-processing.service.ts
- #999 
resolves eclipse-tractusx/traceability-foss#999
=> chore(notifications): 999 fix bug

CHANGELOG.md, frontend/src/app/mocks/services/admin-mock/admin.model.ts, frontend/src/app/modules/core/user/table-settings.service.spec.ts, frontend/src/app/modules/page/admin/core/admin.model.ts, frontend/src/app/modules/page/admin/presentation/contracts/contracts.component.spec.ts, frontend/src/app/modules/page/admin/presentation/contracts/contracts.component.ts, frontend/src/app/modules/page/parts/model/parts.model.ts, frontend/src/app/modules/shared/assembler/parts.assembler.ts, frontend/src/app/modules/shared/components/parts-table/parts-as-built-configuration.model.ts, frontend/src/app/modules/shared/components/parts-table/parts-as-planned-configuration.model.ts, frontend/src/app/modules/shared/components/parts-table/parts-table.component.spec.ts
- #1105 
resolves eclipse-tractusx/traceability-foss#1105
=> chore(contracts): 1105 adjust part reference in contracts

CHANGELOG.md, README.md, dev/README.md
-  appropriate README.md 2
resolves eclipse-tractusx/traceability-foss#1070
=> Chore/#1070 release checks 24.8 part4

CHANGELOG.md, CONTRIBUTING.md, DOCKER_NOTICE.md, INSTALL.md, NOTICE.md, README.md, frontend/DOCKER_NOTICE.md, tx-backend/INSTALL.md
-#1070 Update documentation artefacts according to TRG 1 - Documentation
resolves eclipse-tractusx/traceability-foss#1070
=> Chore/#1070 release checks 24.8 part4 #1070 Update documentation artefacts according to TRG 1 - Documentation

CHANGELOG.md, frontend/src/app/modules/page/dashboard/presentation/dashboard.component.html, frontend/src/app/modules/shared/modules/notification/presentation/notification.component.html, frontend/src/assets/locales/de/common.json, frontend/src/assets/locales/en/common.json
resolves eclipse-tractusx/traceability-foss#941
=> chore(update): 941 - label update

CHANGELOG.md, Dockerfile
Fixes failing workflow https://github.com/eclipse-tractusx/traceability-foss/actions/workflows/quality-checks.yaml
https://github.com/eclipse-tractusx/traceability-foss/actions/runs/10072265123
=> chore(docker): define uid and gid directly in user, instead of variables

CHANGELOG.md, Dockerfile, frontend/DOCKER_NOTICE.md, frontend/Dockerfile
=> chore(update): xxx - analysis of cve

CHANGELOG.md, COMPATIBILITY_MATRIX.md, charts/traceability-foss/CHANGELOG.md
=> chore(release): xxx - create release 13.0.1

CHANGELOG.md, tx-backend/src/main/java/org/eclipse/tractusx/traceability/notification/application/notification/rest/NotificationController.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/notification/domain/base/service/AbstractNotificationService.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/notification/domain/notification/service/NotificationServiceImpl.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/notification/infrastructure/notification/repository/NotificationRepositoryImpl.java, tx-backend/src/test/java/org/eclipse/tractusx/traceability/integration/common/support/NotificationApiSupport.java, tx-backend/src/test/java/org/eclipse/tractusx/traceability/integration/notification/EditNotificationIT.java
resolves eclipse-tractusx/traceability-foss#1122
=> bug 1122 fix editing notification sendTo attribute

CHANGELOG.md, frontend/src/app/modules/page/notifications/detail/notification-detail.component.ts, frontend/src/app/modules/shared/components/table/table.component.html, frontend/src/app/modules/shared/components/table/table.component.ts, frontend/src/assets/locales/de/page.alert.json, frontend/src/assets/locales/de/page.investigation.json, frontend/src/assets/locales/en/page.alert.json, frontend/src/assets/locales/en/page.investigation.json
resolves eclipse-tractusx/traceability-foss#908
=> chore(release): 908 - Changed notification detail view.

CHANGELOG.md, README.md, dev/README.md, docs/concept/#437-adapt-to-changes-of-industry-core/#437-adapt-to-changes-industry-core.md, docs/src/docs/arc42/cross-cutting/domain-concepts.adoc, frontend/src/app/modules/page/admin/presentation/contracts/contracts.component.ts, frontend/src/app/modules/shared/modules/notification/modal/content/notification-modal-content.component.html, frontend/src/app/modules/shared/modules/notification/modal/content/notification-modal-content.component.ts
resolves eclipse-tractusx/traceability-foss#1227
=> chore(release): 1227 - removed scrollbar on approval dialog.

CHANGELOG.md, frontend/src/app/modules/page/admin/core/admin.model.ts, frontend/src/app/modules/shared/components/table/table.component.html
resolves eclipse-tractusx/traceability-foss#1227
=> chore(release): 1227 - fixed null values for datepicker.

.github/workflows/helm-chart-release.yaml
=> chore(release): xxx - release/13.0.2

.github/workflows/dependency-check.yml, .github/workflows/pull_request_issue.yml, CHANGELOG.md
=> chore(release): xxx - fix some vars in github actions.

docs/src/uml-diagrams/arc42/runtime-view/data-consumption-process_part1_tracex_scaling.puml
The sequence diagram has been added to the code repository to illustrate the asynchronous processing flow within the TraceX backend and its interactions with the Digital Twin Registry (DTR) and IRS. The diagram outlines both the current and optimized states of processing aasIDs, detailing how they transition through various statuses and the expectation that data will be available when requested by TraceXFE.
This addition is intended to clarify the sequential processing of data records, the transition to the correct status, and the assumptions regarding data availability in the frontend (TraceXFE). It should enhance understanding of the process flow and the asynchronous nature of the backend operations.
Please ensure to do as many of the following checks as possible, before asking for …
=> chore(release): xxx - high scaling part resolving tracex

.github/workflows/pull-request_backend.yml
This PR refactors the pull-request_backend.yml to split the Sonar step from the Test step. This avoids the test fail even though Sonar was not available.
=> feature: split sonar action from pr action

.github/workflows/trufflehog-secret-scan.yml
Introducing TruffleHog as new secret scanning workflow as a replacement for the recently used GitGuardian.
https://github.com/eclipse-tractusx/traceability-foss/issues/1371
=> chore: Added trufflehog secret scanning GitHub workflow

frontend/src/app/modules/core/auth/auth.service.ts
There was a bug, when keycloak did not provide authTime which results in a null pointer on our side. 
Be compatible to latest keycloak (25)
- Removal of authTime field to prevent null pointers
Refs: [266 (portal)](https://github.com/eclipse-tractusx/portal-iam/issues/266)
=> fix: [TRACEX-528] remove authTime to support keycloak 25

CHANGELOG.md, tx-cucumber-tests/src/test/java/org/eclipse/tractusx/traceability/test/tooling/rest/RestProvider.java
Repaired the changed notification filter to fix e2e tests. 
eclipse-tractusx/sig-release#1327
=> fix: eclipse-tractusx/sig-release#1327 repair filter in broken cucumber tests

charts/traceability-foss/values-int-a-catena-ev.yaml, charts/traceability-foss/values-int-b-catena-ev.yaml
The new release candidate of the connector needs some further adjustments:
https://matrix.to/#/!fgTCQAaMutepjWCuLl:matrix.eclipse.org/$XTO11TpFN2B8buHWk36xzy-k-owwB7Wy56h44wZy1UU?via=matrix.eclipse.org&via=matrix.org
https://github.com/eclipse-tractusx/tractusx-edc/issues/1965
We will force dcp version 8 to avoid this bug. (Workaround solution)
Is part of the deployment for 25.06 release: #1439 
=> fix(values): #1439 edc values to force dcp v08
