charts/traceability-foss/Chart.yaml, charts/traceability-foss/charts/backend/Chart.yaml, charts/traceability-foss/charts/frontend/Chart.yaml
Upgraded helm chart versions to 1.3.2
=> feature: TRACEFOSS-1032 Upgrade version.

.github/workflows/docker-image-branch_frontend.yml, .github/workflows/docker-image-main_frontend.yml, CHANGELOG.md, backend/pom.xml, backend/src/integration/groovy/org/eclipse/tractusx/traceability/common/support/InvestigationsSupport.groovy, backend/src/integration/groovy/org/eclipse/tractusx/traceability/infrastructure/edc/blackbox/EdcControllerIT.groovy, backend/src/integration/groovy/org/eclipse/tractusx/traceability/investigations/adapters/rest/PublisherInvestigationsControllerIT.groovy, backend/src/integration/groovy/org/eclipse/tractusx/traceability/investigations/adapters/rest/ReadInvestigationsControllerIT.groovy, backend/src/main/java/org/eclipse/tractusx/traceability/assets/application/AssetFacade.java, backend/src/main/java/org/eclipse/tractusx/traceability/infrastructure/jpa/notification/NotificationEntity.java, backend/src/main/java/org/eclipse/tractusx/traceability/investigations/adapters/jpa/PersistentInvestigationsRepository.java, backend/src/main/java/org/eclipse/tractusx/traceability/investigations/domain/model/Investigation.java, backend/src/main/java/org/eclipse/tractusx/traceability/investigations/domain/model/Notification.java, backend/src/main/java/org/eclipse/tractusx/traceability/investigations/domain/service/InvestigationsPublisherService.java, backend/src/test/java/org/eclipse/tractusx/traceability/assets/infrastructure/adapters/rest/dashboard/DashboardControllerTest.java, backend/src/test/java/org/eclipse/tractusx/traceability/infrastructure/edc/blackbox/notification/ContractNegotiationDtoTest.java, backend/src/test/java/org/eclipse/tractusx/traceability/infrastructure/edc/blackbox/notification/ContractOfferDescriptionTest.java, backend/src/test/java/org/eclipse/tractusx/traceability/infrastructure/edc/blackbox/notification/NegotiationIdTest.java, backend/src/test/java/org/eclipse/tractusx/traceability/infrastructure/edc/blackbox/notification/NegotiationInitiateRequestDtoTest.java, backend/src/test/java/org/eclipse/tractusx/traceability/infrastructure/edc/blackbox/notification/TransferIdTest.java, backend/src/test/java/org/eclipse/tractusx/traceability/investigations/adapters/rest/InvestigationsControllerTest.java, backend/src/test/java/org/eclipse/tractusx/traceability/investigations/domain/model/InvestigationReceiverTest.java, charts/traceability-foss/Chart.yaml, charts/traceability-foss/charts/backend/Chart.yaml, charts/traceability-foss/charts/frontend/Chart.yaml, docs/src/docs/administration/backend-configuration.adoc, docs/src/docs/administration/frontend-configuration.adoc, docs/src/docs/administration/installation.adoc, frontend/src/index.html
- Some unit tests for better code quality
- Fixed edc notification flow bug
- Updated org.springframework/spring-expression from 6.0.6 to 6.0.7
- Updated net.minidev/json-smart from 2.4.8 to 2.4.10
- Updated documentation of application
=> Build & Test & Notification Flow Improvements

.github/workflows/trivy.yml
=> Activate trivy image scan for backend

backend/src/test/java/org/eclipse/tractusx/traceability/infrastructure/edc/blackbox/cache/EndpointDataReferenceTest.java, backend/src/test/java/org/eclipse/tractusx/traceability/infrastructure/edc/blackbox/catalog/CatalogRequestTest.java, backend/src/test/java/org/eclipse/tractusx/traceability/infrastructure/edc/blackbox/catalog/CatalogTest.java, backend/src/test/java/org/eclipse/tractusx/traceability/infrastructure/edc/blackbox/negotiation/ContractNegotiationTest.java, backend/src/test/java/org/eclipse/tractusx/traceability/infrastructure/edc/blackbox/negotiation/ContractRejectionTest.java, backend/src/test/java/org/eclipse/tractusx/traceability/infrastructure/edc/blackbox/offer/ContractDefinitionTest.java, backend/src/test/java/org/eclipse/tractusx/traceability/infrastructure/edc/blackbox/query/CriterionTest.java, backend/src/test/java/org/eclipse/tractusx/traceability/infrastructure/edc/blackbox/transfer/DataAddressTest.java, backend/src/test/java/org/eclipse/tractusx/traceability/infrastructure/edc/blackbox/transfer/DataFlowRequestTest.java, backend/src/test/java/org/eclipse/tractusx/traceability/infrastructure/edc/blackbox/transfer/TransferRequestDtoTest.java, backend/src/test/java/org/eclipse/tractusx/traceability/infrastructure/edc/blackbox/transfer/TransferTypeTest.java, backend/src/test/java/org/eclipse/tractusx/traceability/infrastructure/edc/notificationcontract/service/EdcNotificationContractServiceTest.java, backend/src/test/java/org/eclipse/tractusx/traceability/infrastructure/edc/notificationcontract/service/contract/model/EdcContractDefinitionCriteriaTest.java
- DashboardControllerTest
- InvestigationsControllerTest
- EdcNotificationContractServiceTest
- EdcContractDefinitionCriteriaTest 
- EndpointDataReferenceTest 
- CatalogTest and CatalogRequestTest 
- DataAddressTest 
- DataFlowRequestTest 
- TransferTypeTest 
- TransferRequestDtoTest 
- ContractDefinitionTest 
- ContractRejectionTest
=> Improve Quality with Unit Tests

CHANGELOG.md, dev/EDC_PROVIDER_DATA_UPLOAD.md, frontend/src/app/modules/page/admin/admin.routing.ts, frontend/src/app/modules/page/admin/presentation/admin.component.html, frontend/src/app/modules/page/admin/presentation/admin.component.ts, frontend/src/app/modules/page/admin/presentation/bpn-configuration/bpn-configuration.component.ts
- Created BPN - BPN - EDC configuration page with mappings for notification flow
- Added in FE with `wip` flag
=> Deactivated new feature in frontend

charts/traceability-foss/Chart.yaml, charts/traceability-foss/charts/backend/Chart.yaml, charts/traceability-foss/charts/frontend/Chart.yaml
- Version upgraded to appVersion 3.2.0 and helmChart 1.3.3
=> Feature/3.2.0 Version Upgrade

.github/workflows/helm-test.yaml, charts/traceability-foss/charts/backend/values.yaml, charts/traceability-foss/values.yaml
- fixed backend chart to work with postgresql
=> backend chart changes to work with  postgresql

.github/workflows/docker-image-main_backend.yml, .github/workflows/docker-image-main_frontend.yml, .github/workflows/docker-image-tag-release.yaml, DOCKER_NOTICE.md, README.md
- Added logic to push image to docker hub for eclipse-tractusx repository
=> Added docker hub push logic

.github/workflows/pull-request_backend.yml, CHANGELOG.md, dev/README.md, tx-backend/openapi/traceability-foss-backend.json, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/domain/model/Asset.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/infrastructure/adapters/feign/registry/RegistryService.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/infrastructure/adapters/metrics/RegistryLookupMetric.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/infrastructure/adapters/rest/assets/AssetsController.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/infrastructure/adapters/rest/assets/SyncAssets.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/infrastructure/adapters/rest/metrics/registrylookup/RegistryLookupMetricsController.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/bpn/mapping/domain/model/BpnEdcMapping.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/bpn/mapping/infrastructure/adapters/rest/BpnEdcMappingController.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/bpn/mapping/infrastructure/adapters/rest/BpnEdcMappingRequest.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/common/config/OpenApiConfig.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/common/model/PageResult.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/investigations/adapters/rest/InvestigationsController.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/investigations/adapters/rest/model/InvestigationData.java, tx-backend/src/main/resources/application-dev.yml
- Added logic to push image to docker hub for eclipse-tractusx repository
- Updated path of digital twin registry for dev environment
=> Updated path of digital twin registry for dev environment

CHANGELOG.md, DEPENDENCIES_BACKEND
=> RELEASE 4.0.0

.github/workflows/docker-image-main_backend.yml, .github/workflows/docker-image-tag-release.yaml, .github/workflows/pull-request_backend.yml, .github/workflows/trivy.yml, CHANGELOG.md, Dockerfile, tx-backend/pom.xml
- jib to build and push docker images
=> replaced jib with docker-build-push action

dev/README.md, tx-backend/openapi/traceability-foss-backend.json, tx-backend/src/main/java/org/eclipse/tractusx/traceability/common/config/ErrorHandlingConfig.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/common/config/SecurityConfig.java, tx-backend/src/main/resources/db/migration/V26__bpn_edc_url_new_mappings.sql
---
name: Fix Quality Alerts
---
- Fix for Quality Alerts Notifications authorization problem
- Fix for Investigation Notification Update authorization problem
- update fallback bpn mappings not having to update it each time environment is started
- added logging to auth failure handler
- updated dev/README.md
=> Quality Alert fix

charts/traceability-foss/Chart.yaml, charts/traceability-foss/charts/backend/Chart.yaml, charts/traceability-foss/charts/frontend/Chart.yaml, frontend/package.json
---
name: update helm chart to for new release version
about: 'template for PRs that ensures basic information is provided'
title: 'feat: TRACEFOSS-XXX 4.1.0 , helm charts 1.3.9'
---
=> helm-charts-1.3.9

CHANGELOG.md, DEPENDENCIES_BACKEND, pom.xml, tx-backend/openapi/traceability-foss-backend.json, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/application/rest/AssetsController.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/application/rest/DashboardController.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/bpn/mapping/infrastructure/adapters/rest/BpnEdcMappingController.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/infrastructure/edc/notificationcontract/controller/EdcNotificationContractController.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/qualitynotification/application/alert/rest/AlertController.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/qualitynotification/application/investigation/rest/InvestigationsController.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/shelldescriptor/application/RegistryController.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/shelldescriptor/application/RegistryLookupMetricsController.java
---
name: Pull Request for swagger security issues
---
Fix Swagger UI security issues
- Added default response types to apis
=> (chore): swagger-security-issues

CHANGELOG.md, charts/traceability-foss/Chart.yaml, charts/traceability-foss/charts/backend/Chart.yaml, charts/traceability-foss/charts/frontend/Chart.yaml, frontend/package.json
=> release helm-charts-1.3.10

.github/workflows/import-about-info.yaml, CHANGELOG.md, frontend/src/app/modules/page/alerts/core/alert-detail.facade.ts, frontend/src/app/modules/shared/pipes/format-partlist-semantic-data-model-to-camelcase.pipe.ts, frontend/src/assets/notice/legal-notice.json
- Added about component with additional Workflow to load repo info into the component
=> Added about component with additional workflow to display legal information

.github/workflows/helm-test.yaml, CHANGELOG.md, charts/traceability-foss/charts/backend/templates/deployment.yaml, charts/traceability-foss/charts/backend/templates/tests/test-connection.yaml, charts/traceability-foss/charts/frontend/templates/tests/test-connection.yaml, charts/traceability-foss/values.yaml, tx-backend/src/integration/resources/stubs/irs/get/jobs/id/response_200_downward_asPlanned.json, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/infrastructure/base/irs/model/response/JobDetailResponse.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/infrastructure/base/irs/model/response/Submodel.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/common/config/ApplicationStartupConfig.java, tx-backend/src/test/java/org/eclipse/tractusx/traceability/common/config/ApplicationStartupConfigTest.java, tx-backend/testdata/CX_Testdata_MessagingTest_v0.0.5.json
- Updated Irs helm chart to 6.3.0
- Update EDC dependencies to 0.1.3
- Update implementation to use EDC 0.5.0
- Environment [TRACEFOSS-2164]: HTTP Requests for syncing the submodel server inoperable~~
=> IRS & EDC Update

tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/infrastructure/base/irs/model/response/JobDetailResponse.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/infrastructure/base/irs/model/response/Submodel.java
- expanded accepted aspecttypes of testdata
=> Expanded accepted aspecttypes of testdata

CHANGELOG.md, charts/traceability-foss/charts/backend/templates/deployment.yaml, charts/traceability-foss/charts/backend/values.yaml, charts/traceability-foss/values.yaml, dev/README.md, tx-backend/src/main/java/org/eclipse/tractusx/traceability/infrastructure/edc/properties/EdcProperties.java, tx-backend/src/main/resources/application-dev.yml, tx-backend/src/main/resources/application-e2e-a.yml, tx-backend/src/main/resources/application-e2e-b.yml, tx-backend/src/main/resources/application-int-a.yml, tx-backend/src/main/resources/application-int-b.yml, tx-backend/src/main/resources/application-int.yml, tx-backend/src/main/resources/application-integration.yml, tx-backend/src/main/resources/application-test.yml, tx-backend/src/main/resources/application.yml
- Moved all parts of app config to helm charts to be fully configurable
=> Application config moved to values

charts/traceability-foss/Chart.yaml, charts/traceability-foss/charts/backend/Chart.yaml, charts/traceability-foss/charts/frontend/Chart.yaml, frontend/package.json
=> TRACEFOSS-XXX release 6.0.0

.tractusx
Follow the format of the example in this [TRG](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-5).
=> chore: format .tractusx

frontend/src/assets/notice/legal-notice.json
=> feature: TRACEFOSS-2474 fixed issues..

CHANGELOG.md, DEPENDENCIES_BACKEND, pom.xml, tx-backend/src/main/java/org/eclipse/tractusx/traceability/shelldescriptor/application/ShellDescriptorRefreshJob.java
- Spring Boot Update from:  3.0.7 to 3.1.2
- Spring Core Update from: 6.0.8 to 6.0.11
=> chore: Spring Security update

DEPENDENCIES_BACKEND
- Updated dependencies check result
=> Dependencies check update

CHANGELOG.md
=> chore: TRACEFOSS-XXX create release 9.0.0-rc1

.github/workflows/dependency-check.yml, .github/workflows/e2e-tests-xray_frontend.yml, .gitignore, CHANGELOG.md, DEPENDENCIES_BACKEND, README.md, dependency_check/suppressions.xml, frontend/cypress/support/step_definitions/dashboard.ts, frontend/cypress/support/step_definitions/login.ts, frontend/src/app/modules/shared/components/table-settings/table-settings.component.ts, tx-backend/pom.xml, tx-models/pom.xml
- Cypress Login to E2E Environment to enable cypress e2e tests.
- Fixed table-settings reset bug
- Functionality to indicate that no Dependency Check findings occur in a PR
- Badge to show successful Dependency Check status
- Mitigated Dependency Check findings
=> chore/feature:  Cypress login, dependency check

pom.xml
- upgraded irs client lib version
=> upgrade irs-lib

CHANGELOG.md, DEPENDENCIES_BACKEND, frontend/src/app/mocks/services/parts-mock/partsAsBuilt/partsAsBuilt.model.ts, frontend/src/app/modules/page/parts/model/parts.model.ts, frontend/src/app/modules/shared/assembler/parts.assembler.ts, frontend/src/app/modules/shared/components/multi-select-autocomplete/multi-select-autocomplete.component.html, frontend/src/app/modules/shared/components/multi-select-autocomplete/multi-select-autocomplete.component.spec.ts, frontend/src/app/modules/shared/components/multi-select-autocomplete/multi-select-autocomplete.component.ts, frontend/src/app/modules/shared/components/parts-table/parts-table.component.html, frontend/src/app/modules/shared/helper/filter-helper.spec.ts, frontend/src/app/modules/shared/helper/filter-helper.ts, frontend/src/assets/locales/de/common.json, frontend/src/assets/locales/en/common.json, tx-backend/openapi/traceability-foss-backend.json, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/application/asbuilt/mapper/AssetAsBuiltResponseMapper.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/application/asplanned/mapper/AssetAsPlannedResponseMapper.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/application/base/mapper/AssetBaseResponseMapper.java, tx-backend/src/test/java/org/eclipse/tractusx/traceability/integration/assets/AssetAsBuiltControllerByIdIT.java, tx-backend/src/test/java/org/eclipse/tractusx/traceability/integration/assets/AssetAsPlannedControllerByIdIT.java, tx-models/src/main/java/assets/response/base/AssetBaseResponse.java
- Changed datepicker in FE to date range picker
- Assets response have now list of notification ids rather than count of existing notifications
- Frontend adapt to backend api changes for activeAlerts and activeInvestigations
=> changed date picker to date range in FE

DEPENDENCIES_BACKEND, frontend/src/app/modules/shared/modules/notification/modal/approve/approve-notification-modal.component.spec.ts, frontend/src/app/modules/shared/modules/notification/modal/approve/approve-notification-modal.component.ts
=> Fix UI button 

CHANGELOG.md, COMPATIBILITY_MATRIX.md, charts/traceability-foss/Chart.yaml, charts/traceability-foss/charts/backend/Chart.yaml, charts/traceability-foss/charts/frontend/Chart.yaml, frontend/package.json, frontend/src/app/modules/page/parts/core/parts.helper.spec.ts, frontend/src/app/modules/page/parts/core/parts.helper.ts, frontend/src/app/modules/page/parts/presentation/parts.component.html, frontend/src/app/modules/page/parts/presentation/parts.component.ts, frontend/src/app/modules/shared/components/multi-select-autocomplete/multi-select-autocomplete.component.html, frontend/src/app/modules/shared/components/multi-select-autocomplete/multi-select-autocomplete.component.scss, frontend/src/app/modules/shared/components/multi-select-autocomplete/multi-select-autocomplete.component.spec.ts, frontend/src/app/modules/shared/components/multi-select-autocomplete/multi-select-autocomplete.component.ts, frontend/src/app/modules/shared/components/parts-table/parts-table.component.html, frontend/src/app/modules/shared/components/parts-table/parts-table.component.spec.ts, frontend/src/app/modules/shared/components/parts-table/parts-table.component.ts, frontend/src/app/modules/shared/helper/filter-helper.spec.ts, frontend/src/app/modules/shared/helper/filter-helper.ts, frontend/src/app/modules/shared/pipes/format-part-semantic-data-model-to-camelcase.pipe.spec.ts, frontend/src/app/modules/shared/pipes/format-part-semantic-data-model-to-camelcase.pipe.ts, frontend/src/app/modules/shared/service/parts.service.ts, frontend/src/assets/locales/de/common.json, frontend/src/assets/locales/en/common.json, frontend/src/theme/base.scss
- Added autocompletion and local filter selection on parts table
=> autocompletion and local filter selecttion on parts table

.github/workflows/docker-image-branch_frontend.yml, .github/workflows/docker-image-main_frontend.yml, .github/workflows/docker-image-tag-release.yaml, .github/workflows/helm-test.yaml, .github/workflows/trivy.yml, CHANGELOG.md, Dockerfile, charts/traceability-foss/values.yaml, docs/src/docs/user/user-manual.adoc, frontend/Dockerfile, tx-backend/testdata/database_dumps/README.md
- DEPENDENCIES_FRONTEND, SECURITY.md, NOTICE.md, LICENSE file to frontend docker image
- Added a step-by-step guide to register a server in pgAdmin in the database dump README
- Documentation about technical users
- Fixed helm repository path for backend & frontend (wrong prefix)
- apk upgrade in docker image built as requested by TRG 4.02
=> Added licensing information to frontend build

charts/traceability-foss/Chart.yaml, charts/traceability-foss/charts/backend/Chart.yaml, charts/traceability-foss/charts/frontend/Chart.yaml, frontend/package.json
=> chore: TRACEFOSS-XXX release 9.0.0-rc3

CHANGELOG.md, charts/traceability-foss/CHANGELOG.md
=> chore(release): 10.7.0

.github/workflows/e2e-tests-xray_frontend.yml, DEPENDENCIES_BACKEND, frontend/.gitignore, frontend/cypress/support/step_definitions/login.ts, frontend/package.json, frontend/src/app/modules/core/known-route.ts, frontend/src/app/modules/page/dashboard/presentation/dashboard.component.html, frontend/src/app/modules/shared/model/notification.model.ts
=> chore: fix Cypress tests

DEPENDENCIES_BACKEND, DEPENDENCIES_FRONTEND, tx-backend/pom.xml, tx-models/src/main/java/common/PageResult.java
fixes the following issues:
- kics finding a5375be3-521c-43bb-9eab-e2432e368ee4
- "Reference equality test on strings" (CWE-597)
- CVE-2024-25710 by updating org.apache.commons:commons-compress to 1.26.0
=> chore: fix security issues

docs/src/docs/arc42/runtime-view/policies.adoc, docs/src/uml-diagrams/arc42/runtime-view/policies/policy-assets.puml, docs/src/uml-diagrams/arc42/runtime-view/policies/policy-notifications.puml, docs/src/uml-diagrams/arc42/runtime-view/policies/policy-startup-configuration.puml, docs/src/uml-diagrams/arc42/runtime-view/policies/policy-startup-notification-contract.puml
- improve policy store documentation
=> chore: #596 rework policy store documentation

pom.xml, tx-backend/pom.xml
=> chore(release): 10.8.1

CHANGELOG.md, COMPATIBILITY_MATRIX.md, charts/traceability-foss/CHANGELOG.md
=> chore(release):xxx release/11.0.2

CONTRIBUTING.md, docs/RELEASE.md
- Update githhok description in CONTRIBUTING.md 
=> Update CONTRIBUTING.md add git-hooks

README.md
Adding a vision and misson statement to the README. 
=> chore(README):[#1028]Add vision and mission statement to README

tx-backend/src/main/java/org/eclipse/tractusx/traceability/notification/domain/base/service/NotificationPublisherService.java
=> feature(refactoring):xxx fixed nullpointer

frontend/src/app/mocks/services/policy-mock/policy.model.spec.ts, frontend/src/app/mocks/services/policy-mock/policy.model.ts, frontend/src/app/modules/page/admin/presentation/policy-management/policy-editor/policy-editor.component.ts, frontend/src/app/modules/page/policies/model/policy.model.ts
resolves eclipse-tractusx/traceability-foss#832
=> feature(policy): #832 fix test

tx-backend/src/main/java/org/eclipse/tractusx/traceability/notification/application/notification/mapper/NotificationMessageMapper.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/notification/domain/base/model/Notification.java
=> feature(chore):962 fix mapping fields

frontend/src/app/modules/shared/modules/notification/modal/actions/notification-action-modal.component.ts
=> chore(notification): xxx refresh notification on error

frontend/src/app/modules/shared/components/notification-reason/notification-reason.component.spec.ts
=> chore(notification): 962 fix message direction

frontend/src/app/modules/page/admin/presentation/contracts/contract-detail/contract-detail.component.html, frontend/src/app/modules/shared/components/view-selector/view-selector.component.html, frontend/src/app/modules/shared/components/view-selector/view-selector.component.spec.ts
#912 Added checkmarks to view selectors
resolves eclipse-tractusx/traceability-foss#912
=> chore(uux): 912 added checkmark to view selector

tx-backend/src/main/java/org/eclipse/tractusx/traceability/notification/infrastructure/notification/model/NotificationEntity.java
=> feature(chore):962 fixed sonar issues.

CHANGELOG.md, docs/src/uml-diagrams/arc42/cross-cutting/domain-model/domain-model-quality-notifications.puml, docs/src/uml-diagrams/arc42/cross-cutting/erm-trace-x.puml, tx-backend/src/main/java/org/eclipse/tractusx/traceability/notification/infrastructure/notification/model/NotificationEntity.java, tx-cucumber-tests/src/test/resources/features/10_TRACEFOSS-2354.feature, tx-cucumber-tests/src/test/resources/features/11_TRACEFOSS-1125.feature, tx-cucumber-tests/src/test/resources/features/1_TRACEFOSS-1393.feature, tx-cucumber-tests/src/test/resources/features/2_TRACEFOSS-600.feature, tx-cucumber-tests/src/test/resources/features/3_TRACEFOSS-938.feature, tx-cucumber-tests/src/test/resources/features/4_TRACEFOSS-936.feature, tx-cucumber-tests/src/test/resources/features/5_TRACEFOSS-1625.feature, tx-cucumber-tests/src/test/resources/features/6_TRACEFOSS-382.feature, tx-cucumber-tests/src/test/resources/features/7_TRACEFOSS-1090.feature, tx-cucumber-tests/src/test/resources/features/8_TRACEFOSS-608.feature, tx-cucumber-tests/src/test/resources/features/9_TRACEFOSS-607.feature
- #962 Removed initial notification message for notification flow
=> feature(chore):962 fixed notifications / cucumber tests

CHANGELOG.md, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/application/asbuilt/mapper/AssetAsBuiltFieldMapper.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/application/asplanned/mapper/AssetAsPlannedFieldMapper.java, tx-backend/src/test/java/org/eclipse/tractusx/traceability/integration/assets/AssetAsBuiltControllerFilterValuesIT.java
#1037 extended autocomplete api by contractAgreementId
=> feature(chore):1037 extended autocomplete api by contractAgreementId

frontend/src/app/modules/shared/components/notification-reason/notification-reason.component.html, frontend/src/app/modules/shared/components/notification-reason/notification-reason.component.ts
resolves eclipse-tractusx/traceability-foss#753
=> chore(messages): 753 correctly display messages

.github/workflows/dependency-check.yml, .github/workflows/sonar-scan-backend.yml
Fix path of sonar code coverage
=> feature(chore):xxx fixed old paths

tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/application/base/service/AssetBaseService.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/domain/base/AssetRepository.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/domain/base/service/AbstractAssetBaseService.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/infrastructure/asbuilt/repository/AssetAsBuiltRepositoryImpl.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/infrastructure/asplanned/repository/AssetAsPlannedRepositoryImpl.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/common/config/ApplicationStartupConfig.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/contracts/application/service/ContractService.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/contracts/domain/model/ContractAgreement.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/contracts/domain/repository/ContractRepository.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/contracts/domain/service/ContractServiceImpl.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/contracts/infrastructure/repository/ContractRepositoryImpl.java, tx-backend/src/main/resources/db/migration/R__create_contract_agreement_view.sql, tx-backend/src/test/java/org/eclipse/tractusx/traceability/integration/common/support/AssetsSupport.java
Fix flyway script and refactored to table instead of using a view.
=> feature(chore):985 Fixed contractagreement view script.

frontend/src/app/modules/page/admin/presentation/policy-management/deletion-dialog/deletion-dialog.component.html, frontend/src/app/modules/page/admin/presentation/policy-management/deletion-dialog/deletion-dialog.component.scss, frontend/src/app/modules/page/admin/presentation/policy-management/policy-editor/policy-editor.component.html
#832 Added UUX feedback
resolves eclipse-tractusx/traceability-foss#832
=> chore(policies): 832 added layout feedback

.github/workflows/helm-test.yaml
- #685 
resolves eclipse-tractusx/traceability-foss#685
=> chore(actions): 685 specify node image on helm test action manually

tx-backend/src/main/java/org/eclipse/tractusx/traceability/common/config/ApplicationStartupConfig.java
Fix variable switch on asbuilt / asplanned.
=> feature(chore):985 fix bug.

frontend/src/app/modules/page/admin/presentation/policy-management/policies/policies.component.ts, frontend/src/assets/locales/de/page.admin.json, frontend/src/assets/locales/en/page.admin.json
#832 
resolves eclipse-tractusx/traceability-foss#832
=> chore(policy): 832 layout feedback

frontend/src/app/modules/page/notifications/detail/edit/notification-edit.component.html, frontend/src/app/modules/page/notifications/detail/edit/notification-edit.component.ts, frontend/src/app/modules/shared/components/request-notification-new/notification-new-request.component.ts
- #984 
resolves eclipse-tractusx/traceability-foss#984
=> chore(uux): 984 validation on notification save hover

CHANGELOG.md, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/infrastructure/asbuilt/repository/AssetAsBuiltRepositoryImpl.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/infrastructure/asplanned/repository/AssetAsPlannedRepositoryImpl.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/infrastructure/base/irs/JobRepositoryImpl.java, tx-backend/src/test/java/org/eclipse/tractusx/traceability/integration/assets/infrastructure/base/IrsCallbackControllerIT.java, tx-backend/src/test/resources/stubs/irs/get/jobs/id/response_200.json
=> bug: #1082 fix parts synchronization

frontend/src/app/modules/shared/service/parts.service.ts, frontend/src/assets/locales/de/common.json, frontend/src/assets/locales/en/common.json
=> chore(registry): xxx changed request parameter

frontend/src/assets/locales/en/common.json
=> chore(contracts): 985 change labelling

CHANGELOG.md, tx-backend/src/main/java/org/eclipse/tractusx/traceability/notification/infrastructure/edc/model/EDCNotificationFactory.java
=> feature(chore):xxx - fixed notification description.

tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/infrastructure/asbuilt/repository/AssetAsBuiltRepositoryImpl.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/infrastructure/asplanned/repository/AssetAsPlannedRepositoryImpl.java
=> bug: xxx fix DataIntegrityViolationException by preventing dirty reads

frontend/src/assets/locales/de/common.json
resolves eclipse-tractusx/traceability-foss#1009
=> chore(notifications): 1009 change labelling

charts/traceability-foss/charts/backend/values.yaml, charts/traceability-foss/charts/frontend/values.yaml
=> feature(xxx):xxx updated image values

CHANGELOG.md, docs/api/traceability-foss-backend.json, frontend/src/app/modules/shared/components/multi-select-autocomplete/autocomplete-strategy.ts, frontend/src/app/modules/shared/service/notification.service.spec.ts, frontend/src/app/modules/shared/service/notification.service.ts, frontend/src/app/modules/shared/service/parts.service.ts, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/application/asbuilt/rest/AssetAsBuiltController.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/application/asplanned/rest/AssetAsPlannedController.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/application/base/request/SearchableAssetsRequest.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/application/base/request/SearchableNotificationsRequest.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/application/base/service/AssetBaseService.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/domain/base/service/AbstractAssetBaseService.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/notification/application/notification/rest/NotificationController.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/notification/application/notification/service/NotificationService.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/notification/domain/base/service/AbstractNotificationService.java, tx-backend/src/test/java/org/eclipse/tractusx/traceability/assets/domain/base/service/AbstractAssetBaseServiceTest.java, tx-backend/src/test/java/org/eclipse/tractusx/traceability/integration/assets/AssetAsBuiltControllerSearchValuesIT.java, tx-backend/src/test/java/org/eclipse/tractusx/traceability/integration/assets/AssetAsPlannedControllerSearchValuesIT.java, tx-backend/src/test/java/org/eclipse/tractusx/traceability/integration/notification/alert/AlertControllerSearchValuesIT.java, tx-backend/src/test/java/org/eclipse/tractusx/traceability/integration/notification/investigation/InvestigationControllerSearchValuesIT.java
=> feat: rework autocomplete api for notifications endpoint

CHANGELOG.md, docs/api/traceability-foss-backend.json, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/application/asbuilt/rest/AssetAsBuiltController.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/application/asplanned/rest/AssetAsPlannedController.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/application/base/mapper/OwnerTypeMapper.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/notification/application/notification/rest/NotificationController.java, tx-backend/src/main/java/org/eclipse/tractusx/traceability/notification/base/mapper/NotificationSideTypeMapper.java, tx-models/src/main/java/assets/request/SearchableAssetsRequest.java, tx-models/src/main/java/assets/response/base/OwnerType.java, tx-models/src/main/java/notification/NotificationSideType.java, tx-models/src/main/java/notification/request/SearchableNotificationsRequest.java
=> refactor: refactor according to feedback

CHANGELOG.md, frontend/src/app/modules/shared/components/parts-table/parts-table.component.scss, frontend/src/app/modules/shared/components/table/table.component.scss
- #1025 
resolves eclipse-tractusx/traceability-foss#1025
=> chore(contracts): #1025 fix overlapping table actions

charts/traceability-foss/Chart.yaml
resolves eclipse-tractusx/traceability-foss#1216
=> feature: #1216 upgrade EDC version to 0.7.1

docs/src/docs/arc42/runtime-view/policies.adoc, docs/src/uml-diagrams/arc42/runtime-view/policies/policy-crud-notification-contract.puml
resolves eclipse-tractusx/traceability-foss#1190
=> feature: #1190 update documentation

frontend/src/assets/locales/en/common.json
resolves eclipse-tractusx/traceability-foss#1224
=> chore(contracts):1224 - feedback tooltip.

CHANGELOG.md, COMPATIBILITY_MATRIX.md, charts/traceability-foss/CHANGELOG.md
=> release(13.0.0):xxx - release 13.0.0

tx-backend/src/main/java/org/eclipse/tractusx/traceability/policies/application/mapper/PolicyMapper.java
=> bug: #xxx fix edc policy creation by sending empty lists as null

CHANGELOG.md, COMPATIBILITY_MATRIX.md, charts/traceability-foss/Chart.yaml
=> chore: xxx update irs version

tx-backend/testdata/CX_Testdata_MessagingTest_v0.0.14-ev.json, tx-backend/testdata/CX_Testdata_MessagingTest_v0.0.14.json
=> chore(update): xxx - adapt testdata.

.github/workflows/argo.yml
=> chore(update): xxx - fix regex for version input

CHANGELOG.md, pom.xml
=> chore: xxx update springboot to 3.2.8 from 3.2.5

tx-backend/src/main/java/org/eclipse/tractusx/traceability/discovery/infrastructure/repository/FeignDiscoveryRepositoryImpl.java
resolves eclipse-tractusx/traceability-foss#1112
=> chore(update): 1112 - discoveryfinder fix

CHANGELOG.md, COMPATIBILITY_MATRIX.md
Registry upgrade - Compatibility Matrix update
resolves eclipse-tractusx/traceability-foss#1244
=> chore(update): 1244 - update registry

tx-backend/testdata/import-test-data-0DWF_v0.0.14.json, tx-backend/testdata/import-test-data-0UKM_v0.0.14.json
=> chore(update): xxx - updated testdata.

frontend/src/app/modules/page/dashboard/core/dashboard.assembler.ts
=> chore(update): xxx - fix dashboard

CHANGELOG.md
=> chore(xxx): fix Known knowns

.github/workflows/xray-cucumber-association.yaml
resolves eclipse-tractusx/traceability-foss#1235
=> feature: 1235 fix github action

.github/workflows/e2e-tests-xray_frontend.yml
=> chore: xxx adapt cypress tests

.github/workflows/e2e-tests-xray_frontend.yml
=> chore(release): xxx - fix test

frontend/src/app/modules/shared/modules/notification/modal/content/notification-modal-content.component.ts
resolves eclipse-tractusx/traceability-foss#1227
=> chore(release): 1227 - fixed links

CHANGELOG.md, tx-backend/collection/tracex.json
resolves eclipse-tractusx/traceability-foss#866
=> chore(release): 866 - Insomnia update.

CHANGELOG.md, COMPATIBILITY_MATRIX.md, charts/traceability-foss/CHANGELOG.md
=> chore(release): xxx - release/13.0.2

charts/traceability-foss/Chart.yaml
=> chore: Upgrading edc.

charts/traceability-foss/values.yaml
- Change 1
- Change 2
- Change 3
=> fix: helm upgrade workflow

charts/traceability-foss/charts/backend/templates/deployment.yaml, charts/traceability-foss/values.yaml
- Change 1
- Change 2
- Change 3
=> chore: TRACEX-XXX add api feature

tx-backend/src/main/resources/application.yml
- add missing discovery type for dtr client
=> fix(tx-backend): add missing discovery type for dtr client

charts/traceability-foss/Chart.yaml
- update subchart versions of frontend and backend
=> fix(charts): update subchart versions of frontend and backend

charts/traceability-foss/values-base.yaml, charts/traceability-foss/values-int-a-catena-ev.yaml, charts/traceability-foss/values-int-b-catena-ev.yaml
- add missing irs callback config and switch to internal urls
=> fix(charts): add missing irs callback config and switch to internal urls

charts/traceability-foss/values-int-a-catena-ev.yaml, charts/traceability-foss/values-int-b-catena-ev.yaml
=> fix(charts): fix irs callback urls

charts/traceability-foss/charts/backend/values.yaml, charts/traceability-foss/values.yaml
Remove the trusted port logic, not needed anymore.
Updating discovery type value
=> chore: Removal of trusted port and updating discoveryType value

CHANGELOG.md, frontend/package.json, frontend/yarn.lock
Fix a security issue due to a CVE
CVE-2024-21538
- Guarantee higher version (^7.0.6) via resolutions in package json
Refs: [1416](https://github.com/eclipse-tractusx/traceability-foss/issues/1416)
=> fix(frontend): 1416 fix cross-spawn dependency

CHANGELOG.md, frontend/package.json, frontend/yarn.lock
add resolution to fix Path traversal in webpack-dev-middleware
CVE-2024-29180
- add resolution
Refs: [1416](https://github.com/eclipse-tractusx/traceability-foss/issues/1416)
=> fix(frontend): 1416 add resolution to fix Path traversal in webpack-dev-middleware

CHANGELOG.md, frontend/package.json, frontend/yarn.lock
Fix Denial of service in http-proxy-middleware
[CVE-2024-21536](https://nvd.nist.gov/vuln/detail/CVE-2024-21536)
- add resolution to package.json
Refs: [1416](https://github.com/eclipse-tractusx/traceability-foss/issues/1416)
=> fix(frontend): 1416 add resolution to fix Denial of service in http-proxy-middleware

CHANGELOG.md, frontend/package.json, frontend/yarn.lock
Semver has some high vulnerabilities which needs to be fixed.
CVE-2022-25883
- Add resolution for semver fix
Refs: [1416](https://github.com/eclipse-tractusx/traceability-foss/issues/1416)
=> fix(frontend): 1416 provide fix for semver vulnerability

CHANGELOG.md
- Change 1
- Change 2
- Change 3
=> chore: release 14.0.1

CHANGELOG.md, COMPATIBILITY_MATRIX.md, pom.xml
=> release: Create release

charts/traceability-foss/Chart.yaml, charts/traceability-foss/charts/backend/Chart.yaml, charts/traceability-foss/charts/frontend/Chart.yaml
Create Release for charts 1.4.2
=> release: Update chart versions.

charts/traceability-foss/values-int-a-catena-ev.yaml, charts/traceability-foss/values-int-b-catena-ev.yaml
As a DevOps we need to repair the current deployment of Catena-X Test Env due to missing values. See #1451
=> fix(charts): 1451 - adjust values to repair catena deployment

CHANGELOG.md, COMPATIBILITY_MATRIX.md, charts/traceability-foss/CHANGELOG.md, charts/traceability-foss/Chart.yaml, tx-backend/src/main/java/org/eclipse/tractusx/traceability/common/config/SecurityConfig.java
As Developers we want to guarantee a safe and maintained repository according to the Tractus-X Release Guildelines and update all dependencies. #1439
=> fix: 1439 upgrade dependencies and adjust actuator whitelisting

pom.xml
=> fix: 1439 bump irs client version for trace-foss

COMPATIBILITY_MATRIX.md, charts/traceability-foss/Chart.yaml, charts/traceability-foss/charts/backend/Chart.yaml, charts/traceability-foss/charts/frontend/Chart.yaml
Upgrade connector version which fixes the EDC Bug: https://github.com/eclipse-tractusx/tractusx-edc/issues/1962
#1439 
=> chore(charts): #1439 chart upgrade edc

pom.xml
resolves traceability-foss#1463
=> chore(1463): bump spring-security-core and apache-tomcat-embed version.
